skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_verified_builds = "7esAkToYq1hTYMPhVuN68DkLJjdAAnyCBkEjM8TLHUue"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
